### ISSUE TITLE
409 error when using github repo for storage

### ISSUE THREAD

**Issue by matikin9** [mavoweb/mavo#215] opened 2017-06-03 18:30 UTC
I'm trying to get the GitHub repo storage working... it usually saves fine the first time I make an edit (the json file exists and has changes saved to it), but then the second time I try to save I get an HTTP 409 error:

![image](https://cloud.githubusercontent.com/assets/1873072/26756030/9cf23480-484e-11e7-8279-5d014cb8eb20.png)

The code I'm using is super basic, and I'm using my own GitHub account so i should have all permissions:
```
<main mv-app="homepage" mv-storage="https://github.com/matikin9/mavo-test">
   <p property="description">
      Text here.
   </p>
</main>
```

I tried linking directly to the json file (```https://github.com/matikin9/mavo-test/blob/master/homepage.json```) and got the same result.

**Comment by LeaVerou** [comment] 2017-06-04 09:40
FWIW it doesn't look like you're making any mistakes to me, this must be some weird bug. 

Some questions to help me figure it out:

- Do you get the 409 after refreshing and trying to save? If not, does it go away if you refresh and try to save? 
- Does the time between them make a difference?
- Is the pattern always "first edit works, second, third etc fails" or different?

**Comment by matikin9** [comment] 2017-06-06 05:23
The pattern does seem to be "first edit works, subsequent edits fail".  Refreshing does not always allow me to save again.  Although it seems clearing my browser's cached images and files DOES consistently allow me to save...

**Comment by gentle-media** [comment] 2017-06-13 22:18
I get the 409 error when the cursor is still in the field of the element (focus) and I click on 'Save'.
For this reason I also can't use the `mv-autosave` attribute. It keeps on throwing the 409 error while I'm typing and MAVO tries to autosave at the background.

**Comment by LeaVerou** [comment] 2017-06-14 16:06
Thank you all! I haven't been very responsive on this because I have family visiting, but it's at the top of my list of things to work on this weekend!

**Comment by Tarqez** [comment] 2017-06-14 20:27
Hello everybody, I get the same 409 error.
My test:

Login --> edit --> 1st save --> OK
2nd, 3rd, ... nth save (with or without editing) FAIL if it happens within a certain amount of time.
After this time, (n+1)th save SUCCESS.
This amount of time, from the first save, seems to change every test but it is less that 1 minute in my case.

**Comment by LeaVerou** [comment] 2017-06-14 21:34
Interesting! @matikin9 Is time a factor in your case?

FWIW, I was able to reproduce is as well, but it seems to vary. In my case I only got it once, on the 2nd time. So it may well be that it's time related.

**Comment by Tarqez** [comment] 2017-06-17 10:08
Hello, maybe the following helps.

Incidentally, I found the problem in the _Chrome cache_.
It's time-related because of how long the cache persists.

Disabling the cache with _developer tools_, **error 409** disappears.

To further investigate the problem, I repeated the experiment described in my previous comment. 

I found that as long as Chrome gets GitHub responses from the cache, error 409 appears.
As soon as stops getting from the cache no more error. Look at the picture.

![409](https://user-images.githubusercontent.com/2567359/27252059-256b9462-5355-11e7-83d4-5ca4bc687038.png)

**Comment by LeaVerou** [comment] 2017-06-20 17:22
@Tarqez My own testing seems to confirm this. Indeed, I get the 409 when I save for a 2nd+ time, unless dev tools is open which disables cache. @matikin9 is that the case with you as well?

**Comment by LeaVerou** [comment] 2017-06-20 17:23
Actually, even if I uncheck "Disable cache" in the dev tools, it still fixes the error. Bizarre!

**Comment by LeaVerou** [comment] 2017-06-20 18:47
I cannot seem to reproduce the issue anywhere but I have a theory about why it may be happening. I just pushed a fix that —assuming my theory is correct— fixes it. Please let me know, and reopen this if it's not fixed!

**Closed** 2017-06-20 18:46 UTC

**Comment by matikin9** [comment] 2017-06-20 18:48
Awesome, I'll try it out!

**Comment by Tarqez** [comment] 2017-06-21 07:17
It works!
The same tests now pass.
No cache, no problem.
Thank you.

**Comment by matikin9** [comment] 2017-07-01 21:53
yay :D no more error for me too!
