### ISSUE TITLE
Unexpected Behavior on mv-default

### ISSUE THREAD

**Issue by lukesmurray** [mavoweb/mavo#439] opened 2019-01-10 21:48 UTC
This issue can be reproduced on the mavo website [here](https://mavo.io/docs/properties#mv-default).

Set y to 6 and the increment x from 5 to 7. Even though y has been changed as soon as x is equal to y the numbers fall back in sync. This might be the desired behavior but it feels confusing especially with the text above...

Note that changing the first number changes the second, until you edit the second and make it different:

**Comment by LeaVerou** [comment] 2019-01-12 16:47
Duplicate of #100

**Closed by LeaVerou** 2019-01-12 16:47 UTC
