### ISSUE TITLE
Using an invalid name in mv-bar results in an exception and stack trace

### ISSUE THREAD

**Issue by forsyth** [mavoweb/mavo#758] opened 2021-08-15 15:40 UTC
By accident I wrote mv-bar="nologin" instead of mv-bar="no-login" and because I didn't notice the typo, was at first bemused that the page didn't work at all, just defaults, as if my data had vanished. Removing the option restored things so, checking the console, I found the immediate cause:

mavo-nodeps.js:2459 Uncaught (in promise) TypeError: Cannot read property 'create' of undefined
    at mavo-nodeps.js:2459
    at Array.forEach (<anonymous>)
    at n.constructor (mavo-nodeps.js:2451)
    at new n (deps.js:1)
    at new Mavo (mavo-nodeps.js:144)
    at mavo-nodeps.js:827
    at Array.map (<anonymous>)
    at Function.init (mavo-nodeps.js:827)
    at mavo-nodeps.js:1177
(anonymous) @ mavo-nodeps.js:2459
constructor @ mavo-nodeps.js:2451
n @ deps.js:1
Mavo @ mavo-nodeps.js:144
(anonymous) @ mavo-nodeps.js:827
init @ mavo-nodeps.js:827
(anonymous) @ mavo-nodeps.js:1177
async function (async)
(anonymous) @ mavo-nodeps.js:1023
(anonymous) @ mavo-nodeps.js:1180

in 		this.controls.forEach(id => {
			let o = _.controls[id];
                        ...
			if (o.create) {
				this[id] = o.create.call(this.mavo, this[id]);

... _.controls[id] is not set for "nologin" (or nonsense, such as "frodo"). Since there are other references to _.controls[id] it's probably best for getControls to complain and discard useless ones if it can.

**Comment by LeaVerou** [comment] 2021-08-16 13:16
Confirmed. Testcase: https://codepen.io/leaverou/pen/vYmwYPJ?editors=1100

**Comment by LeaVerou** [comment] 2021-08-16 13:19
Thank you for reporting this! It should be pretty easy to fix.

**Comment by LeaVerou** [comment] 2021-08-16 13:23
> ... _.controls[id] is not set for "nologin" (or nonsense, such as "frodo"). Since there are other references to _.controls[id] it's probably best for getControls to complain and discard useless ones if it can.

Just noticed this. Am I reading this correctly that you would be interested in submitting a pull request? 😄

**Comment by forsyth** [comment] 2021-08-16 13:27
Unfortunately I've only just started using Mavo let alone studied the
internals, and at the moment I'd probably just spoil the existing
cleanliness of the code!

**Comment by Nisbij** [comment] 2021-08-19 18:47
> By accident I wrote mv-bar="nologin" instead of mv-bar="no-login" and because I didn't notice the typo, was at first bemused that the page didn't work at all, just defaults, as if my data had vanished. Removing the option restored things so, checking the console, I found the immediate cause:
> 
> mavo-nodeps.js:2459 Uncaught (in promise) TypeError: Cannot read property 'create' of undefined
> at mavo-nodeps.js:2459
> at Array.forEach ()
> at n.constructor (mavo-nodeps.js:2451)
> at new n (deps.js:1)
> at new Mavo (mavo-nodeps.js:144)
> at mavo-nodeps.js:827
> at Array.map ()
> at Function.init (mavo-nodeps.js:827)
> at mavo-nodeps.js:1177
> (anonymous) @ mavo-nodeps.js:2459
> constructor @ mavo-nodeps.js:2451
> n @ deps.js:1
> Mavo @ mavo-nodeps.js:144
> (anonymous) @ mavo-nodeps.js:827
> init @ mavo-nodeps.js:827
> (anonymous) @ mavo-nodeps.js:1177
> async function (async)
> (anonymous) @ mavo-nodeps.js:1023
> (anonymous) @ mavo-nodeps.js:1180
> 
> in this.controls.forEach(id => {
> let o = _.controls[id];
> ...
> if (o.create) {
> this[id] = o.create.call(this.mavo, this[id]);
> 
> ... _.controls[id] is not set for "nologin" (or nonsense, such as "frodo"). Since there are other references to _.controls[id] it's probably best for getControls to complain and discard useless ones if it can.

That's a great solution, didn't pick up on it at first but it makes more sense now. Just a question, I am interested in working on this, is it fine to pick up this issue?

**Comment by LeaVerou** [comment] 2021-08-19 18:51
> Just a question, I am interested in working on this, is it fine to pick up this issue?

Yup! Thank you!

**Comment by Nisbij** [comment] 2021-08-20 17:54
I am making a list of all the possible values for mv-bar and checking whether 'id', is in the list. Is this the right way to go or am I making the code more bulkier?

**Comment by Nisbij** [comment] 2021-08-23 10:21
I am having issues with testing it on my local server because of CORB 

> Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost:8000/dist/maps/mavo.es5.js.map with MIME type application/octet-stream. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by DmitrySharabin** [comment] 2021-08-23 14:14
> I am making a list of all the possible values for mv-bar and checking whether 'id', is in the list. Is this the right way to go or am I making the code more bulkier?

Hi there! 👋🏻

As far as I am aware, the `Mavo.UI.Bar` class has the `controls` property where all the supported controls are already defined:
https://github.com/mavoweb/mavo/blob/b60cd7aa88f301d034e7aa134095ee2b4a481681/src/ui.bar.js#L229

And there is also a code snippet that you might find useful to get the `id`s of all the supported controls as an array:
https://github.com/mavoweb/mavo/blob/b60cd7aa88f301d034e7aa134095ee2b4a481681/src/ui.bar.js#L197

**Comment by Nisbij** [comment] 2021-08-23 19:26
if we just check for positive and negative to be -1, we can say that the input property does not belong to supported controls. But how do I give an error, is just giving a console.log() enough?

						[https://github.com/mavoweb/mavo/blob/b60cd7aa88f301d034e7aa134095ee2b4a481681/src/ui.bar.js#L213-L214](url)

**Comment by DmitrySharabin** [comment] 2021-08-24 09:55
> But how do I give an error, is just giving a console.log() enough?

For the cases like this one, you can use the static `warn` method of the `Mavo` class. It does all you need and also some extra things we find beneficial. Please have a look at its definition here:
https://github.com/mavoweb/mavo/blob/d571ccffe8b7a99973758bf30db16ba273d563f1/src/mavo.js#L841-L851

Here you can find an example of its usage:
https://github.com/mavoweb/mavo/blob/d571ccffe8b7a99973758bf30db16ba273d563f1/src/mavo.js#L1093

**Comment by joyously** [comment] 2021-08-24 14:06
Is that usage translated?

**Comment by Nisbij** [comment] 2021-08-25 06:11
I have made the changes and committed it, can someone check it

**Closed** 2021-10-12 17:21 UTC
Labels: bug, good first issue
