### ISSUE TITLE
@mv-default with an expression on <select> appends an extra <option> with this expression

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#741] opened 2021-07-01 08:22 UTC
Testcase: https://codepen.io/dmitrysharabin/pen/vYmOYdg?editors=1000

Git bisect showed this commit as the first bad one: 6acb4088d3f538b81b59bb7bde30173ff6f6f62b.

Interestingly, [this issue](https://github.com/mavoweb/mavo/issues/716) found by @karger is not the case anymore.

**Comment by LeaVerou** [comment] 2023-09-02 12:51
> Interestingly, [this issue](https://github.com/mavoweb/mavo/issues/716) found by @karger is not the case anymore.

You mean you can't reproduce it anymore? Shouldn't we close it then?

**Comment by LeaVerou** [comment] 2023-09-02 12:58
So this happened when we started adding disabled `mv-volatile` options to display values that are not among the `<select>` options. I wonder if we could fix it by either setting a timeout and removing the unneeded volatile options then.
Or we could debug why [this line](https://github.com/mavoweb/mavo/commit/6acb4088d3f538b81b59bb7bde30173ff6f6f62b#diff-164073e00c54f8fffd373ebc51c2f38c35c30933e4118580c3fe6850d2e775a5R494) is not called, despite the property value actually changing.

**Comment by DmitrySharabin** [comment] 2023-09-02 18:12
> > Interestingly, [this issue](https://github.com/mavoweb/mavo/issues/716) found by @karger is not the case anymore.
> 
> 
> 
> You mean you can't reproduce it anymore? Shouldn't we close it then?
> 
Actually, it is still broken. 🤦‍♂️

**Comment by DmitrySharabin** [comment] 2023-09-15 11:25
> Or we could debug why [this line](https://github.com/mavoweb/mavo/commit/6acb4088d3f538b81b59bb7bde30173ff6f6f62b#diff-164073e00c54f8fffd373ebc51c2f38c35c30933e4118580c3fe6850d2e775a5R494) is not called, despite the property value actually changing.

It looks like this line is not called because it's in the `edit()` method, but we don't edit the property but set its value. So, I believe we should move it to the `editorValue()` setter to fix the regression. I already did some time ago [here](https://github.com/mavoweb/mavo/commit/6398058bb0b2ee3faf1cac8ed2022e5d953c5e3b). I can send a separate PR with the fix if you like.

**Closed** 2023-09-23 16:49 UTC
Labels: bug, REGRESSION, Priority: high
